owner: axone-protocol
repo: status
sites:
  - name: Axone Web Site
    url: "https://axone.xyz"
  - name: Axone Documentation Site
    url: "https://docs.axone.xyz"
  - name: Axone Agentic Airdrop Web Site
    url: "https://airdrop.axone.xyz"
  - name: Axone Faucet
    url: "https://faucet.axone.xyz"
  - name: Axone Explorer
    url: "https://explore.axone.xyz"
  - name: S3 Axone
    url: "https://s3.axone.xyz/you_shall_not_pass.gandalf"
    expectedStatusCodes:
      - 401
  - name: Nemeton Program Web Site
    url: "https://nemeton.okp4.network"

status-website:
  cname: status.axone.xyz
  theme: dark
  logoUrl: >-
    https://raw.githubusercontent.com/axone-protocol/status/main/assets/axone-m0-white-transparent-1024.png
  name: ""
  favicon: "https://raw.githubusercontent.com/axone-protocol/status/main/assets/favicon.png"
  introTitle: "**Axone** status and uptime page"
  introMessage: This page shows current status of the Axone services and API.
  navbar:
    - title: Status
      href: /
    - title: Axone
      href: "https://axone.xyz"
    - title: GitHub
      href: "https://github.com/$OWNER"
assignees:
  - ccamel

i18n:
  footer: "[Axone](https://axone.xyz) / [Docs](https://docs.axone.xyz) / [Discord](https://discord.gg/axone) / [X](https://twitter.com/axonexyz) / [Contribute](https://github.com/axone-protocol)"
