owner: okp4
repo: status
sites:
  - name: OKP4 Web Site
    url: "https://okp4.network"
  - name: OKP4 Documentation Site
    url: "https://docs.okp4.network"
  - name: OKP4 Faucet
    url: "https://faucet.okp4.network"
  - name: OKP4 Explorer
    url: "https://explore.okp4.network"
  - name: Nemeton Program Web Site
    url: "https://nemeton.okp4.network"
  - name: RPC okp4-nemeton-1
    url: "https://api.testnet.okp4.network/cosmos/base/tendermint/v1beta1/blocks/latest"
  - name: Subquery GraphQL API okp4-nemeton-1
    method: POST
    url: "https://api.subquery.network/sq/okp4/nemeton-1"
    headers:
      - "Accept: application/json"
      - "Content-Type: application/json"
      - "Host: api.subquery.network"
    body: '{ "query": "{blocks(last: 1) { nodes { chainId height } } }" }'
    __dangerous__body_degraded: errors

status-website:
  cname: status.okp4.network
  theme: light
  logoUrl: >-
    https://raw.githubusercontent.com/okp4/brand-kit/main/01-Logos/okp4-square-signs-without-background.png
  faviconSvg: >-
    https://raw.githubusercontent.com/okp4/brand-kit/main/01-Logos/favicon-gradient.svg
  favicon: "https://raw.githubusercontent.com/okp4/brand-kit/main/01-Logos/favicon.png"
  name: OKP4 status
  introTitle: "**OKP4** status and uptime page"
  introMessage: This page shows current status of the OKP4 services and API.
  navbar:
    - title: Status
      href: /
    - title: OKP4
      href: "https://okp4.network"
    - title: GitHub
      href: "https://github.com/$OWNER"
assignees:
  - amimart
  - ccamel

i18n:
  footer: "[OKP4](https://okp4/network) / [Docs](https://docs.okp4.network) / [Discord](https://discord.gg/okp4) / [Twitter](https://twitter.com/OKP4_Protocol) / [Contribute](https://github.com/okp4)"
