owner: axone-protocol
repo: status
sites:
  - name: Axone Web Site
    url: "https://axone.xyz"
  - name: Axone Documentation Site
    url: "https://docs.axone.xyz"
  - name: Axone Faucet
    url: "https://faucet.okp4.network"
  - name: Axone Explorer
    url: "https://explore.axone.xyz"
  - name: KatAI
    url: "https://katai.axone.xyz"
  - name: Nemeton Program Web Site
    url: "https://nemeton.okp4.network"
  - name: Subquery GraphQL API nemeton-1
    method: POST
    url: "https://api.subquery.network/sq/okp4/nemeton-1"
    headers:
      - "Accept: application/json"
      - "Content-Type: application/json"
      - "Host: api.subquery.network"
    body: '{ "query": "{blocks(last: 1) { nodes { chainId height } } }" }'
    __dangerous__body_degraded: errors

status-website:
  cname: status.axone.xyz
  theme: dark
  logoUrl: >-
    https://raw.githubusercontent.com/axone-protocol/status/main/assets/axone-m0-white-transparent-1024.png
  name: ""
  favicon: "https://raw.githubusercontent.com/axone-protocol/status/main/assets/favicon.png"
  introTitle: "**Axone** status and uptime page"
  introMessage: This page shows current status of the Axone services and API.
  navbar:
    - title: Status
      href: /
    - title: Axone
      href: "https://axone.xyz"
    - title: GitHub
      href: "https://github.com/$OWNER"
assignees:
  - amimart
  - ccamel

i18n:
  footer: "[Axone](https://axone.xyz) / [Docs](https://docs.axone.xyz) / [Discord](https://discord.gg/axone) / [X](https://twitter.com/axonexyz) / [Contribute](https://github.com/axone-protocol)"
